// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGU9eFsCHslyuCoR36HT6JRFcoBVXDKf0',
    appId: '1:458438708644:web:9e746e6e05ed852c094531',
    messagingSenderId: '458438708644',
    projectId: 'salon-albasha',
    authDomain: 'salon-albasha.firebaseapp.com',
    storageBucket: 'salon-albasha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdl-jwif3o05YBL4A1dnK8XDz2K7uUu6Y',
    appId: '1:458438708644:android:868707f4ea5207bc094531',
    messagingSenderId: '458438708644',
    projectId: 'salon-albasha',
    storageBucket: 'salon-albasha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiVeS6Wj7Sx3y5U8iD1YHH8cqfVKJZwlY',
    appId: '1:458438708644:ios:3faa763e8e915f29094531',
    messagingSenderId: '458438708644',
    projectId: 'salon-albasha',
    storageBucket: 'salon-albasha.firebasestorage.app',
    iosBundleId: 'com.example.projectNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiVeS6Wj7Sx3y5U8iD1YHH8cqfVKJZwlY',
    appId: '1:458438708644:ios:3faa763e8e915f29094531',
    messagingSenderId: '458438708644',
    projectId: 'salon-albasha',
    storageBucket: 'salon-albasha.firebasestorage.app',
    iosBundleId: 'com.example.projectNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGU9eFsCHslyuCoR36HT6JRFcoBVXDKf0',
    appId: '1:458438708644:web:5723fe16830b98a3094531',
    messagingSenderId: '458438708644',
    projectId: 'salon-albasha',
    authDomain: 'salon-albasha.firebaseapp.com',
    storageBucket: 'salon-albasha.firebasestorage.app',
  );
}
